Exercício 3 - Página Web
viniccius-dev/exercicios-de-nivelamento-orion-bootcamp pull request #3
Opened 2024-10-04 06:26 UTC by viniccius-dev

2024-10-04 11:39 UTC, aLiviaMs commented on exercicios.ts
> +function countVowels(word: string): number {
Algumas funções/métodos nao estao documentadas no padrao ts-doc

2024-10-04 11:40 UTC, aLiviaMs requested changes
Só esse pequeno ajuste na doc

2024-10-04 19:26 UTC, samuelcamilocosta commented
a branch está com conflitos e precisa resolver para poder mergear o PR

2024-10-04 22:09 UTC, aLiviaMs approved these changes

2024-10-05 00:48 UTC, samuelcamilocosta approved these changes

2024-10-05 00:51 UTC, merged